view_distance_radius: 40
test_iterations: 1
frontier_replan_steps: 50
a_star_replan_steps: 10
required_coverage: 0.95
wall_number: 29
explored_wall_number: 85
explored_free_number: 218
maps: ["maps/star.tmj"]
save_file: "results"
render: True
distance_to_goal_before_replan: 20
max_frontiers_in_section: 10